/*
 * MIT
 *
 * Copyright (c) 2026 HyperPROBE Labs, KaliAssistant. All Rights Reserved.
 *
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <stdint.h>
#include <sys/types.h>

#include <winsock2.h>
#include <windows.h>
#include <direct.h>
#include <tlhelp32.h>
#pragma comment(lib, "ws2_32.lib")
#define mkdir(path, mode) _mkdir(path)
#define rmdir _rmdir
#define PATH_SEP "\\"
#define LOCALHOST "127.0.0.1"

#define PORT 18080
#define BUFFER_SIZE 8192
#define STRINGIFY(x) #x

#define TMP_SRVDIR "hpevbsrvweb"

typedef struct {
    const char *filename;
    const char *mime_type;
    const unsigned char *data;
    size_t size;
} FileResource;

 // File resources (generated by build script)
extern const FileResource file_resources[];
extern const int file_resources_count;

// Forward declarations
int extract_resources(void);
const char *get_mime_type(const char *filename);
void handle_client(SOCKET client_socket);
void cleanup_resources(void);
void open_browser(const char *url);
int start_http_server(void);
int check_existing_server(void);
void show_error_dialog(const char *title, const char *message);

DWORD WINAPI thread_handler(LPVOID arg);

void enable_ansi(void)
{
    HANDLE hOut = GetStdHandle(STD_OUTPUT_HANDLE);

    DWORD mode;
    if (GetConsoleMode(hOut, &mode))
    {
        mode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
        SetConsoleMode(hOut, mode);
    }
}

void disable_quick_edit(void)
{
    HANDLE hIn = GetStdHandle(STD_INPUT_HANDLE);

    DWORD mode;
    if (GetConsoleMode(hIn, &mode))
    {
        mode &= ~ENABLE_QUICK_EDIT_MODE;
        mode |= ENABLE_EXTENDED_FLAGS;

        SetConsoleMode(hIn, mode);
    }
}

int main() {
    disable_quick_edit();
    enable_ansi();
    SetConsoleOutputCP(CP_UTF8);
    printf("\e[0;34m");
    printf(R"(                               ___  __    ___  ___    __     __       _           )""\n");
    printf(R"(  /\  /\_   _ _ __   ___ _ __ / _ \/__\  /___\/ __\  /__\   / /  __ _| |__  ___   )""\n");
    printf(R"( / /_/ / | | | '_ \ / _ \ '__/ /_)/ \// //  //__\// /_\    / /  / _` | '_ \/ __|  )""\n");
    printf(R"(/ __  /| |_| | |_) |  __/ | / ___/ _  \/ \_// \/  \//__   / /__| (_| | |_) \__ \_ )""\n");
    printf(R"(\/ /_/  \__, | .__/ \___|_| \/   \/ \_/\___/\_____/\__/   \____/\__,_|_.__/|___(_))""\n");
    printf(R"(        |___/|_|                                                                  )""\n");
    printf("\n\e[0;37m");
    printf(R"(Copyright (C) 2026 HyperPROBE Labs, KaliAssistant. All rights reserved.)""\n");
    printf("\n\e[0;32m\n");

    printf("╔════════════════════════════════════════════════════╗ \n");
    printf("║  MP19-7MF-SK6812-EVB Client - Web UI Server  v1.0  ║ \n");
    printf("║  Starting HTTP Server...                           ║ \n");
    printf("╚════════════════════════════════════════════════════╝ \n\n");
    printf("\e[0m");
    // Initialize winsock early on Windows
    WSADATA wsa_data;
    if (WSAStartup(MAKEWORD(2, 2), &wsa_data) != 0) {
        fprintf(stderr, "[-] WSAStartup failed\n");
        return 1;
    }
    // Check if server is already running
    printf("[*] Checking for existing server on port %d...\n", PORT);
    if (check_existing_server() != 0) {
        fprintf(stderr, "\e[1;31m[-] ERROR: A server is already running on port %d\n\e[0m", PORT);
        fprintf(stderr, "\e[1;31m[-] Please close the existing process first\n\e[0m");

        char error_msg[512];
        snprintf(error_msg, sizeof(error_msg),
                 "Client Server is already running on port %d.\n\n"
                 "Please close the existing process before starting a new one.",
                 PORT);
        show_error_dialog("Server Already Running", error_msg);

        WSACleanup();
        return 1;
    }
    printf("[+] No existing server found\n\n");

    // Extract resources to ramfs
    printf("[*] Extracting resources to webfs...\n");
    if (extract_resources() != 0) {
        fprintf(stderr, "\e[1;31m[-] Failed to extract resources\n\e[0m");
        show_error_dialog("Error", "Failed to extract resources");
        WSACleanup();
        return 1;
    }
    printf("[+] Resources extracted successfully\n\n");

    // Open browser
    printf("[*] Opening browser...\n");
    char url[256];
    snprintf(url, sizeof(url), "http://localhost:%d", PORT);
    open_browser(url);

    printf("\n[*] Server running on http://localhost:%d\n", PORT);
    printf("[*] Press Ctrl+C to stop...\n\n");

    // Start HTTP server (blocking call)
    int result = start_http_server();

    cleanup_resources();
    return result;
}

void show_error_dialog(const char *title, const char *message) {
    MessageBoxA(NULL, message, title, MB_OK | MB_ICONERROR);
};

int check_existing_server(void) {
    SOCKET test_socket = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (test_socket == INVALID_SOCKET) {
        return 0;  // Can't create socket, assume no server
    }

    struct sockaddr_in addr;
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = inet_addr(LOCALHOST);
    addr.sin_port = htons(PORT);

    // Try to connect to the port
    int result = connect(test_socket, (struct sockaddr *)&addr, sizeof(addr));
    closesocket(test_socket);

    // If connect succeeds, server is running
    if (result == 0) {
        printf("\e[1;31m[!] Server is already running on port %d\n\e[0m", PORT);
        return 1;
    }

    return 0;  // Server not running
}

// Helper function to get the base filename from a path
const char *get_basename(const char *path) {
    const char *p = path;
    const char *last = path;
    
    while (*p) {
        if (*p == '/' || *p == '\\') {
            last = p + 1;
        }
        p++;
    }
    
    return last;
}

int extract_resources(void) {
    char webfs_path[512];
    char rmcmd[512];
        char temp_path[MAX_PATH];
        if (!GetTempPathA(MAX_PATH, temp_path)) {
            fprintf(stderr, "\e[1;31mFailed to get temp path\n\e[0m");
            return 1;
        }
        snprintf(webfs_path, sizeof(webfs_path), "%s%s", temp_path, TMP_SRVDIR);
        // Remove old directory if exists
        snprintf(rmcmd,sizeof(rmcmd), "rmdir /s /q %%temp%%\\%s", TMP_SRVDIR);
        system(rmcmd);

    if (mkdir(webfs_path, 0755) != 0 && errno != EEXIST) {
        perror("mkdir failed");
        return 1;
    }

    // Extract all files
    for (int i = 0; i < file_resources_count; i++) {
        const FileResource *res = &file_resources[i];
        char filepath[1025];
        
        // Get just the filename, not the full path
        const char *basename = get_basename(res->filename);

        snprintf(filepath, sizeof(filepath), "%s\\%s", webfs_path, basename);

        // Write file
        FILE *f = fopen(filepath, "wb");
        if (!f) {
            fprintf(stderr, "\e[1;31mFailed to create file: %s\n\e[0m", filepath);
            perror("fopen failed");
            return 1;
        }

        if (fwrite(res->data, 1, res->size, f) != res->size) {
            perror("fwrite failed");
            fclose(f);
            return 1;
        }

        fclose(f);
        printf("  [+] Extracted: %s (%zu bytes)\n", basename, res->size);
    }

    return 0;
}

const char *get_mime_type(const char *filename) {
    const char *ext = strrchr(filename, '.');
    if (!ext) return "application/octet-stream";

    if (strcmp(ext, ".html") == 0) return "text/html; charset=utf-8";
    if (strcmp(ext, ".js") == 0) return "application/javascript; charset=utf-8";
    if (strcmp(ext, ".css") == 0) return "text/css; charset=utf-8";
    if (strcmp(ext, ".png") == 0) return "image/png";
    if (strcmp(ext, ".jpg") == 0) return "image/jpeg";
    if (strcmp(ext, ".ico") == 0) return "image/x-icon";
    if (strcmp(ext, ".svg") == 0) return "image/svg+xml";
    if (strcmp(ext, ".json") == 0) return "application/json; charset=utf-8";
    if (strcmp(ext, ".woff") == 0) return "font/woff";
    if (strcmp(ext, ".woff2") == 0) return "font/woff2";
    
    return "application/octet-stream";
}

void handle_client(SOCKET client_socket) {
    char buffer[BUFFER_SIZE];
    char request_path[512] = "/";
    unsigned char response_header[BUFFER_SIZE];
    int bytes_received;
    int bytes_sent;

    printf("[*] handle_client: socket=%lld\n", client_socket);
    fflush(stdout);

    // Receive HTTP request
    bytes_received = recv(client_socket, buffer, BUFFER_SIZE - 1, 0);
    if (bytes_received < 0) {
        printf("\e[1;31m[-] recv failed: %s (errno=%d, socket=%lld)\n\e[0m", strerror(errno), errno, client_socket);
        fflush(stdout);
        closesocket(client_socket);
        return;
    }

    if (bytes_received == 0) {
        printf("\e[1;31m[-] Connection closed by client\n\e[0m");
        fflush(stdout);
        closesocket(client_socket);
        return;
    }

    buffer[bytes_received] = '\0';

    printf("[*] Received %d bytes\n", bytes_received);
    printf("[*] First 100 chars: %.100s\n", buffer);
    fflush(stdout);

    // Parse request line (GET /path HTTP/1.1)
    char method[16] = {0};
    sscanf(buffer, "%15s %511s", method, request_path);
    
    printf("[*] Method: %s, Path: %s\n", method, request_path);
    fflush(stdout);

    // Only handle GET requests
    if (strcmp(method, "GET") != 0) {
        const char *error_response = 
            "HTTP/1.1 405 Method Not Allowed\r\n"
            "Content-Type: text/plain\r\n"
            "Content-Length: 18\r\n"
            "Connection: close\r\n"
            "\r\n"
            "405 Method Not Allowed";
        
        send(client_socket, error_response, strlen(error_response), 0);
        closesocket(client_socket);
        return;
    }

    // Remove query string
    char *query = strchr(request_path, '?');
    if (query) *query = '\0';

    // Default to index.html
    if (strcmp(request_path, "/") == 0) {
        strcpy(request_path, "/index.html");
    }

    // Remove leading slash
    const char *filename = request_path + 1;

    printf("[*] Looking for file: %s\n", filename);
    fflush(stdout);

    // Find file in resources by basename match
    const FileResource *resource = NULL;
    for (int i = 0; i < file_resources_count; i++) {
        const char *basename = get_basename(file_resources[i].filename);
        if (strcmp(basename, filename) == 0) {
            resource = &file_resources[i];
            printf("[+] Found resource: %s (%zu bytes)\n", basename, resource->size);
            fflush(stdout);
            break;
        }
    }

    if (resource) {
        const char *mime_type = get_mime_type(filename);
        
        // Build HTTP response header
        int header_size = snprintf((char *)response_header, sizeof(response_header),
                 "HTTP/1.1 200 OK\r\n"
                 "Content-Type: %s\r\n"
                 "Content-Length: %zu\r\n"
                 "Cache-Control: no-cache, must-revalidate\r\n"
                 "Access-Control-Allow-Origin: *\r\n"
                 "Connection: close\r\n"
                 "\r\n",
                 mime_type,
                 resource->size);

        printf("[*] Sending header (%d bytes) for %s\n", header_size, filename);
        fflush(stdout);

        // Send headers
        bytes_sent = send(client_socket, (const char *)response_header, header_size, 0);
        if (bytes_sent < 0) {
            printf("\e[1;31m[-] Failed to send headers for %s: %s\n\e[0m", filename, strerror(errno));
            fflush(stdout);
            closesocket(client_socket);
            return;
        }

        printf("[*] Header sent (%d bytes)\n", bytes_sent);
        fflush(stdout);

        // Send file content in chunks
        size_t sent = 0;
        size_t chunk_size = 65536;  // 64KB chunks
        while (sent < resource->size) {
            size_t to_send = (resource->size - sent < chunk_size) ? 
                             (resource->size - sent) : chunk_size;
            
            bytes_sent = send(client_socket, 
                            (const char *)resource->data + sent, 
                            to_send, 0);
            if (bytes_sent <= 0) {
                printf("\e[1;31m[-] Failed to send data chunk (sent %zu/%zu bytes): %s\n\e[0m", sent, resource->size, strerror(errno));
                fflush(stdout);
                break;
            }
            sent += bytes_sent;
        }

        printf("\e[0;32m[+] 200 OK - %s (%zu bytes sent)\n\e[0m", filename, sent);
        fflush(stdout);
    } else {
        // 404 Not Found
        const char *html_body = "<html><body><h1>404 Not Found</h1></body></html>";
        int body_len = strlen(html_body);
        
        int header_size = snprintf((char *)response_header, sizeof(response_header),
                 "HTTP/1.1 404 Not Found\r\n"
                 "Content-Type: text/html\r\n"
                 "Content-Length: %d\r\n"
                 "Connection: close\r\n"
                 "\r\n",
                 body_len);

        send(client_socket, (const char *)response_header, header_size, 0);
        send(client_socket, html_body, body_len, 0);
        printf("\e[0;31m[-] 404 Not Found - %s\n\e[0m", filename);
        fflush(stdout);
    }

    // Properly close the connection
    shutdown(client_socket, SD_BOTH);
    closesocket(client_socket);
}

DWORD WINAPI thread_handler(LPVOID arg) {
    SOCKET client = (SOCKET)(intptr_t)arg;
    handle_client(client);
    return 0;
}

int start_http_server(void) {
    WSADATA wsa_data;
    SOCKET listen_socket, client_socket;
    struct sockaddr_in server_addr, client_addr;
    int client_addr_len;

    if (WSAStartup(MAKEWORD(2, 2), &wsa_data) != 0) {
        fprintf(stderr, "\e[1;31mWSAStartup failed\n\e[0m");
        return 1;
    }

    listen_socket = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (listen_socket == INVALID_SOCKET) {
        fprintf(stderr, "\e[1;31msocket failed\n\e[0m");
        WSACleanup();
        return 1;
    }

    int reuse = 1;
    setsockopt(listen_socket, SOL_SOCKET, SO_REUSEADDR, (const char *)&reuse, sizeof(reuse));

    server_addr.sin_family = AF_INET;
    server_addr.sin_addr.s_addr = inet_addr(LOCALHOST);
    server_addr.sin_port = htons(PORT);

    if (bind(listen_socket, (struct sockaddr *)&server_addr, sizeof(server_addr)) == SOCKET_ERROR) {
        fprintf(stderr, "\e[1;31m[-] bind failed: %d\n\e[0m", WSAGetLastError());
        fprintf(stderr, "\e[1;31m[-] Port %d is already in use\n\e[0m", PORT);
        closesocket(listen_socket);
        WSACleanup();
        return 1;
    }

    if (listen(listen_socket, SOMAXCONN) == SOCKET_ERROR) {
        fprintf(stderr, "\e[1;31mlisten failed\n\e[0m");
        closesocket(listen_socket);
        WSACleanup();
        return 1;
    }

    printf("[+] HTTP Server listening on http://localhost:%d\n\n", PORT);

    while (1) {
        client_addr_len = sizeof(client_addr);
        client_socket = accept(listen_socket, (struct sockaddr *)&client_addr, &client_addr_len);

        if (client_socket == INVALID_SOCKET) {
            fprintf(stderr, "\e[1;31maccept failed\n\e[0m");
            continue;
        }

        HANDLE thread = CreateThread(NULL, 0, thread_handler, (LPVOID)(intptr_t)client_socket, 0, NULL);
        if (thread) {
            CloseHandle(thread);
        } else {
            closesocket(client_socket);
        }
    }

    closesocket(listen_socket);
    WSACleanup();
    return 0;
}

void open_browser(const char *url) {
    char cmd[512];
    snprintf(cmd, sizeof(cmd), "start \"\" \"%s\"", url);
    printf("[*] Executing: %s\n", cmd);
    fflush(stdout);
    system(cmd);
}



void cleanup_resources(void) {
    char rmcmd[512];
    snprintf(rmcmd, sizeof(rmcmd), "rmdir /s /q %%temp%%\\%s 2>nul", TMP_SRVDIR);
    system(rmcmd);
}
